# Generated by Django 6.0.6 on 2026-07-06 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(default='BR', max_length=3, verbose_name='País de origem')),
                ('continent', models.CharField(blank=True, default='', max_length=3, verbose_name='Continente')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Ano de fabricação')),
                ('denomination', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor de face')),
                ('currency', models.CharField(choices=[('dollar', 'Dólar'), ('euro', 'Euro'), ('pound', 'Libra'), ('real', 'Real'), ('peso', 'Peso'), ('franc', 'Franco'), ('mark', 'Marco'), ('lira', 'Lira'), ('florin', 'Florim'), ('ducat', 'Ducado'), ('crown', 'Coroa'), ('shilling', 'Xelim'), ('drachma', 'Dracma'), ('escudo', 'Escudo'), ('cruzeiro', 'Cruzeiro'), ('reis', 'Réis'), ('other', 'Outra')], default='other', max_length=15, verbose_name='Moeda')),
                ('currency_custom', models.CharField(blank=True, default='', max_length=100, verbose_name='Moeda personalizada')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Descrição / Nome')),
                ('weight_grams', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Peso (g)')),
                ('metal', models.CharField(choices=[('gold', 'Ouro'), ('silver', 'Prata'), ('nickel', 'Níquel'), ('copper', 'Cobre'), ('bronze', 'Bronze'), ('platinum', 'Platina'), ('zinc', 'Zinco'), ('aluminum', 'Alumínio'), ('iron', 'Ferro'), ('bimetallic', 'Bimetálica'), ('other', 'Outro')], default='gold', max_length=15, verbose_name='Metal')),
                ('metal_custom', models.CharField(blank=True, default='', max_length=100, verbose_name='Metal personalizado')),
                ('purity_percentage', models.DecimalField(decimal_places=3, default=90, max_digits=6, verbose_name='Pureza (%)')),
                ('acquisition_date', models.DateField(verbose_name='Data de aquisição')),
                ('acquisition_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor de aquisição (R$)')),
                ('photo', models.ImageField(blank=True, upload_to='coins/photos/', verbose_name='Foto')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coins', to='core.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]