# Generated by Django 6.0.6 on 2026-07-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='denomination',
            field=models.IntegerField(default=0, verbose_name='Valor de face'),
        ),
    ]