# Generated by Django 6.0.6 on 2026-07-04 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Banknote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('usd', 'Dólar (US$)'), ('eur', 'Euro (€)'), ('gbp', 'Libra (£)'), ('brl', 'Real (R$)'), ('other', 'Outra')], default='usd', max_length=10, verbose_name='Moeda')),
                ('currency_custom_label', models.CharField(blank=True, default='', max_length=100, verbose_name='Moeda personalizada')),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor de face')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('acquisition_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor de aquisição (R$)')),
                ('acquisition_date', models.DateField(verbose_name='Data de aquisição')),
                ('serial_number', models.CharField(blank=True, default='', max_length=200, verbose_name='Número de série')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição IRPF')),
                ('vendor_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nome do vendedor')),
                ('vendor_document', models.CharField(blank=True, default='', max_length=20, verbose_name='CPF/CNPJ do vendedor')),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='Data de venda')),
                ('sold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor de venda')),
                ('irpf_group', models.CharField(blank=True, default='', max_length=10, verbose_name='Grupo IRPF')),
                ('irpf_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Código IRPF')),
                ('irpf_include_override', models.BooleanField(blank=True, default=None, null=True, verbose_name='Incluir no IRPF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banknotes', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banknotes', to='core.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, default='', max_length=200, verbose_name='Número de série')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=200, verbose_name='Número da NF')),
                ('type', models.CharField(choices=[('bar', 'Barra'), ('coin', 'Moeda'), ('medal', 'Medalha'), ('other', 'Outro')], default='bar', max_length=10, verbose_name='Tipo')),
                ('type_custom_label', models.CharField(blank=True, default='', max_length=200, verbose_name='Tipo personalizado')),
                ('material', models.CharField(choices=[('gold', 'Ouro'), ('silver', 'Prata'), ('platinum', 'Platina'), ('other', 'Outro')], default='gold', max_length=10, verbose_name='Material')),
                ('material_custom_label', models.CharField(blank=True, default='', max_length=200, verbose_name='Material personalizado')),
                ('purity_percentage', models.DecimalField(decimal_places=3, default=99.9, max_digits=6, verbose_name='Pureza (%)')),
                ('weight_grams', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Peso (g)')),
                ('acquisition_date', models.DateField(verbose_name='Data de aquisição')),
                ('acquisition_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor de aquisição (R$)')),
                ('photo', models.ImageField(blank=True, upload_to='metals/photos/', verbose_name='Foto')),
                ('certificate', models.FileField(blank=True, upload_to='metals/certificates/', verbose_name='Certificado')),
                ('invoice_file', models.FileField(blank=True, upload_to='metals/invoices/', verbose_name='Nota Fiscal')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição IRPF')),
                ('vendor_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nome do vendedor')),
                ('vendor_document', models.CharField(blank=True, default='', max_length=20, verbose_name='CPF/CNPJ do vendedor')),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='Data de venda')),
                ('sold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor de venda')),
                ('irpf_group', models.CharField(blank=True, default='', max_length=10, verbose_name='Grupo IRPF')),
                ('irpf_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Código IRPF')),
                ('irpf_include_override', models.BooleanField(blank=True, default=None, null=True, verbose_name='Incluir no IRPF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metals', to='core.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetalPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='metals/extra_photos/', verbose_name='Foto')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_photos', to='core.metal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
